# Generated by Django 5.0.6 on 2024-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceName', models.CharField(max_length=250)),
                ('Weather', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=500)),
                ('GoogleMap', models.CharField(max_length=800)),
                ('PlaceImage', models.ImageField(upload_to='tourmedia/')),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
